module Reclamo
  VERSION: String

  class Error < StandardError
  end

  class InvalidRequest < Error
  end

  class InvalidParams < Error
  end

  class MethodNotFound < Error
    attr_reader method_name: String

    def initialize: (String) -> void
  end

  class ApplicationError < Error
    attr_reader code: Integer
    attr_reader rpc_data: untyped

    def initialize: (Integer, String, ?untyped) -> void
  end

  class ServerError < Error
    attr_reader code: Integer
    attr_reader rpc_data: untyped

    def initialize: (Integer, String, ?untyped) -> void
  end

  PARSE_ERROR: Integer
  INVALID_REQUEST: Integer
  METHOD_NOT_FOUND: Integer
  INVALID_PARAMS: Integer
  INTERNAL_ERROR: Integer
  SERVER_ERROR_MIN: Integer
  SERVER_ERROR_MAX: Integer
  RESERVED_ERROR_MIN: Integer
  RESERVED_ERROR_MAX: Integer
  ERROR_MESSAGES: Hash[Integer, String]
  GENERIC_ERROR_DATA: String

  class Request
    MAX_NESTING: Integer

    attr_reader method_name: String
    attr_reader params: Array[untyped] | Hash[String, untyped] | nil
    attr_reader id: String | Numeric | nil
    attr_reader context: Hash[Symbol, untyped]

    def initialize: (Hash[String, untyped]) -> void
    def notification?: () -> bool
  end

  module Response
    def self.success: (untyped, untyped) -> Hash[String, untyped]
    def self.error: (Integer, untyped, ?data: untyped, ?message: String?) -> Hash[String, untyped]
  end

  interface _Callable
    def call: (*untyped) -> untyped
  end

  type callable = Proc | Method | _Callable

  class Handler
    def initialize: () -> void
    def expose: (Module | Object, ?namespace: String | Symbol | nil, ?only: Array[Symbol | String] | Symbol | String | nil, ?except: Array[Symbol | String] | Symbol | String | nil, ?descriptions: Hash[Symbol | String, String]?) -> void
    def expose_method: (String | Symbol, ?callable?, ?description: String?) ?{ (*untyped) -> untyped } -> void
    def call: (String, Array[untyped] | Hash[String, untyped] | nil) -> untyped
    def method?: (String) -> bool
    def methods_list: () -> Array[String]
    def methods_info: () -> Array[Hash[String, untyped]]
    def size: () -> Integer
    def empty?: () -> bool
    def freeze: () -> self
  end

  class Server
    attr_reader name: String?
    attr_reader version: String?
    attr_reader description: String?
    attr_reader max_batch_size: Integer?

    def initialize: (?name: String?, ?version: String?, ?description: String?, ?max_batch_size: Integer?, ?expose_errors: bool) -> void
    def expose: (Module | Object, ?namespace: String | Symbol | nil, ?only: Array[Symbol | String] | Symbol | String | nil, ?except: Array[Symbol | String] | Symbol | String | nil, ?descriptions: Hash[Symbol | String, String]?) -> self
    def expose_method: (String | Symbol, ?callable?, ?description: String?) ?{ (*untyped) -> untyped } -> self
    def use: (?only: Array[String | Symbol] | String | Symbol | nil, ?except: Array[String | Symbol] | String | Symbol | nil) { (Request, Proc) -> untyped } -> self
    def to_proc: () -> Proc
    def inspect: () -> String
    def expose_errors?: () -> bool
    def method?: (String) -> bool
    def handle: (String?) -> String?
    alias call handle
    def handle_parsed: (untyped) -> String?
    def methods_list: () -> Array[String]
    def methods_info: () -> Array[Hash[String, untyped]]
    def size: () -> Integer
    def empty?: () -> bool
    def freeze: () -> self
  end

  class Stdio
    def initialize: (Server, ?input: IO, ?output: IO) -> void
    def run: () -> void
    def stop: () -> void
    def running?: () -> bool
  end

  class Rack
    def initialize: (Server) -> void
    def call: (Hash[String, untyped]) -> [Integer, Hash[String, String], Array[String]]
    def freeze: () -> self
  end

  module TestHelpers
    def rpc_call: (Server, String, ?params: untyped, ?id: String | Integer) -> Hash[String, untyped]
    def rpc_notify: (Server, String, ?params: untyped) -> nil
    def rpc_batch: (Server, *Hash[String, untyped]) -> Array[Hash[String, untyped]]?
    def assert_rpc_success: (Hash[String, untyped], ?untyped, ?String?) -> void
    def assert_rpc_error: (Hash[String, untyped], ?code: Integer?, ?message: String?, ?msg: String?) -> void
    def assert_rpc_notification: (Server, String, ?params: untyped, ?msg: String?) -> void
  end
end
