module Reclamo
  VERSION: String

  class Error < StandardError
  end

  class InvalidRequest < Error
  end

  class MethodNotFound < Error
  end

  class ApplicationError < Error
    attr_reader code: Integer
    attr_reader rpc_data: untyped

    def initialize: (Integer, String, ?untyped) -> void
  end

  class ServerError < Error
    attr_reader code: Integer
    attr_reader rpc_data: untyped

    def initialize: (Integer, String, ?untyped) -> void
  end

  PARSE_ERROR: Integer
  INVALID_REQUEST: Integer
  METHOD_NOT_FOUND: Integer
  INVALID_PARAMS: Integer
  INTERNAL_ERROR: Integer
  SERVER_ERROR_MIN: Integer
  SERVER_ERROR_MAX: Integer
  RESERVED_ERROR_MIN: Integer
  RESERVED_ERROR_MAX: Integer
  ERROR_MESSAGES: Hash[Integer, String]

  class Request
    attr_reader method_name: String
    attr_reader params: Array[untyped] | Hash[String, untyped] | nil
    attr_reader id: String | Numeric | nil

    def initialize: (Hash[String, untyped]) -> void
    def notification?: () -> bool
  end

  module Response
    def self.success: (untyped, untyped) -> Hash[String, untyped]
    def self.error: (Integer, untyped, ?data: untyped, ?message: String?) -> Hash[String, untyped]
  end

  class Handler
    def initialize: () -> void
    def expose: (Module | Object, ?namespace: String | Symbol | nil, ?only: Array[Symbol | String]?, ?except: Array[Symbol | String]?) -> void
    def expose_method: (String | Symbol) { (*untyped) -> untyped } -> void
    def call: (String, Array[untyped] | Hash[String, untyped] | nil) -> untyped
    def method?: (String) -> bool
    def methods_list: () -> Array[String]
    def methods_info: () -> Array[Hash[String, untyped]]
    def size: () -> Integer
  end

  class Server
    def initialize: () -> void
    def expose: (Module | Object, ?namespace: String | Symbol | nil, ?only: Array[Symbol | String]?, ?except: Array[Symbol | String]?) -> self
    def expose_method: (String | Symbol) { (*untyped) -> untyped } -> self
    def use: () { (Request, Proc) -> untyped } -> self
    def method?: (String) -> bool
    def handle: (String?) -> String?
    def handle_parsed: (untyped) -> String?
    def methods_list: () -> Array[String]
    def methods_info: () -> Array[Hash[String, untyped]]
    def size: () -> Integer
  end
end
